In [1]:
from bs4 import BeautifulSoup, Comment
import pandas as pd
import os
from io import StringIO

file_paths = ["data/raw/html/Arsenal Goal Logs, Champions League _ FBref.com.html",
              'data/raw/html/Arsenal Goal Logs, Premier League _ FBref.com.html',
              'data/raw/html/Arsenal Match Logs (Goalkeeping), Champions League _ FBref.com.html',
              'data/raw/html/Arsenal Match Logs (Goalkeeping), Premier League _ FBref.com.html',
              'data/raw/html/Arsenal Match Logs (Miscellaneous Stats), Champions League _ FBref.com.html',
              'data/raw/html/Arsenal Match Logs (Miscellaneous Stats), Premier League _ FBref.com.html',
              'data/raw/html/Arsenal Match Logs (Shooting), Champions League _ FBref.com.html',
              'data/raw/html/Arsenal Match Logs (Shooting), Premier League _ FBref.com.html',
              'data/raw/html/Arsenal Scores and Fixtures, Premier League _ FBref.com.html',
              'data/raw/html/Arsenal Scores and Fixtures, Champions League _ FBref.com.html',
              ]


for file_path in file_paths:
    with open(file_path, "r", encoding="utf-8") as f:
        html = f.read()
    print("=" * 50)

    # CHECK RAW HTML
    print("Length of HTML:", len(html))
    print("Number of <table tags:", html.lower().count("<table"))

    print("=" * 50)

    soup = BeautifulSoup(html, "html.parser")

    # NORMAL TABLES
    tables = soup.find_all("table")
    print("BeautifulSoup visible tables:", len(tables))

    print("=" * 50)

    # COMMENT TABLES
    comments = soup.find_all(string=lambda text: isinstance(text, Comment))

    comment_tables = 0

    for comment in comments:
        if "<table" in comment.lower():
            comment_tables += 1

    print("Tables hidden in comments:", comment_tables)

    print("=" * 50)
    
    folder_name = os.path.splitext(os.path.basename(file_path))[0]
    folder_name = folder_name.lower().replace(" ", "_")
            
    output_dir = f"debug_tables/{folder_name}"

    # TRY PANDAS
    try:
        dfs = pd.read_html(StringIO(html))
        print("Pandas found tables:", len(dfs))

        import os

        os.makedirs(output_dir, exist_ok=True)

        for i, df in enumerate(dfs):

            csv_path = f"{output_dir}/table_{i}.csv"

            df.to_csv(csv_path, index=False)

            print(f"Saved {csv_path}")

    except Exception as e:
        print("Pandas failed:")
        print(e)

    print("=" * 50)

==================================================
Length of HTML: 423132
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 495463
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 466051
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 550829
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 458765
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 546206
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 454264
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 543903
Number of <table tags: 11
==================================================
BeautifulSoup visible tables: 11
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 11
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_9.csv
Saved debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_10.csv
==================================================
==================================================
Length of HTML: 466777
Number of <table tags: 10
==================================================
BeautifulSoup visible tables: 10
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 10
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_9.csv
==================================================
==================================================
Length of HTML: 419477
Number of <table tags: 10
==================================================
BeautifulSoup visible tables: 10
==================================================
Tables hidden in comments: 0
==================================================
Pandas found tables: 10
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_0.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_1.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_2.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_3.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_4.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_5.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_6.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_7.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_8.csv
Saved debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_9.csv
==================================================

In [2]:
import os
import glob

base_dir = "debug_tables"

for folder in os.listdir(base_dir):

    folder_path = os.path.join(base_dir, folder)

    if os.path.isdir(folder_path):

        csv_files = sorted(
            glob.glob(f"{folder_path}/*.csv"),
            key=lambda x: int(
                os.path.basename(x)
                .replace("table_", "")
                .replace(".csv", "")
            )
        )

        # keep last 2
        files_to_delete = csv_files[:-2]

        for file in files_to_delete:
            os.remove(file)
            print("Deleted:", file)

Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_goal_logs,_champions_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_goal_logs,_premier_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_champions_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_match_logs_(goalkeeping),_premier_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_champions_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_match_logs_(shooting),_premier_league___fbref.com\table_8.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_champions_league___fbref.com\table_7.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_0.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_1.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_2.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_3.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_4.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_5.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_6.csv
Deleted: debug_tables\arsenal_scores_and_fixtures,_premier_league___fbref.com\table_7.csv

## First table in the folder is stats for Arsenal, 2 table - against Arsenal

In [ ]:
import pandas as pd

goal_logs_cl = pd.read_csv('debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_9.csv')

In [4]:
goal_logs_cl.head(15)

,Rk,Date,Round,Venue,Scorer,Opponent,Start,Minute,Score,Goalkeeper,Assist,Notes
0,1,2025-09-16,League phase,Away,Gabriel Martinelli,Athletic Club,N,72,0-0,Unai Simón,Leandro Trossard,NaN
1,2,2025-09-16,League phase,Away,Leandro Trossard,Athletic Club,N,87,1-0,Unai Simón,Gabriel Martinelli,NaN
2,3,2025-10-01,League phase,Home,Gabriel Martinelli,Olympiacos,Y,12,0-0,Kostas Tzolakis,NaN,NaN
3,4,2025-10-01,League phase,Home,Bukayo Saka,Olympiacos,N,90+2,1-0,Kostas Tzolakis,Martin Ødegaard,NaN
4,5,2025-10-21,League phase,Home,Gabriel Magalhães,Atlético Madrid,Y,57,0-0,Jan Oblak,Declan Rice,NaN
5,6,2025-10-21,League phase,Home,Gabriel Martinelli,Atlético Madrid,Y,64,1-0,Jan Oblak,Myles Lewis-Skelly,NaN
6,7,2025-10-21,League phase,Home,Viktor Gyökeres,Atlético Madrid,Y,67,2-0,Jan Oblak,NaN,NaN
7,8,2025-10-21,League phase,Home,Viktor Gyökeres,Atlético Madrid,Y,70,3-0,Jan Oblak,Gabriel Magalhães,NaN
8,9,2025-11-04,League phase,Away,Bukayo Saka,Slavia Prague,Y*,32,0-0,Jakub Markovič,NaN,NaN
9,10,2025-11-04,League phase,Away,Mikel Merino,Slavia Prague,Y,46,1-0,Jakub Markovič,Leandro Trossard,NaN
10,11,2025-11-04,League phase,Away,Mikel Merino,Slavia Prague,Y,68,2-0,Jakub Markovič,Declan Rice,NaN
11,12,2025-11-26,League phase,Home,Jurriën Timber,Bayern Munich,Y,22,0-0,Manuel Neuer,Bukayo Saka,NaN
12,13,2025-11-26,League phase,Home,Noni Madueke,Bayern Munich,N,69,1-1,Manuel Neuer,Riccardo Calafiori,NaN
13,14,2025-11-26,League phase,Home,Gabriel Martinelli,Bayern Munich,N,77,2-1,Manuel Neuer,Eberechi Eze,NaN
14,15,2025-12-10,League phase,Away,Noni Madueke,Club Brugge,Y,25,0-0,Dani van den Heuvel,Martín Zubimendi,NaN

In [5]:
goal_logs_cl2 = pd.read_csv('debug_tables/arsenal_goal_logs,_champions_league___fbref.com/table_10.csv')
goal_logs_cl2

,Rk,Date,Round,Venue,Scorer,Opponent,Start,Minute,Score,Goalkeeper,Assist,Notes
0,1,2025-11-26,League phase,Home,Lennart Karl,Bayern Munich,Y,32,0-1,David Raya,Serge Gnabry,NaN
1,2,2026-01-20,League phase,Away,Petar Sucic,Inter,Y,18,0-1,David Raya,NaN,NaN
2,3,2026-01-28,League phase,Home,Jorginho Costa,FC Kairat,Y,7,0-1,Kepa Arrizabalaga,NaN,NaN
3,4,2026-01-28,League phase,Home,Ricardinho,FC Kairat,N,90+4,1-3,Kepa Arrizabalaga,Valeriy Gromyko,NaN
4,5,2026-03-11,Round of 16,Away,Robert Andrich,Leverkusen,Y*,46,0-0,David Raya,Álex Grimaldo,NaN
5,6,2026-04-29,Semi-finals,Away,Julián Álvarez,Atlético Madrid,Y,56,0-1,David Raya,NaN,NaN

In [6]:
goal_logs_prem = pd.read_csv('debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_9.csv')
goal_logs_prem.head()

,Rk,Date,Round,Venue,Scorer,Opponent,Start,Minute,Score,Goalkeeper,Assist,Notes
0,1,2025-08-17,Matchweek 1,Away,Riccardo Calafiori,Manchester Utd,Y,13,0-0,Altay Bayındır,NaN,NaN
1,2,2025-08-23,Matchweek 2,Home,Jurriën Timber,Leeds United,Y,34,0-0,Lucas Perri,Declan Rice,NaN
2,3,2025-08-23,Matchweek 2,Home,Bukayo Saka,Leeds United,Y,45+1,1-0,Lucas Perri,Jurriën Timber,NaN
3,4,2025-08-23,Matchweek 2,Home,Viktor Gyökeres,Leeds United,Y,48,2-0,Lucas Perri,Riccardo Calafiori,NaN
4,5,2025-08-23,Matchweek 2,Home,Jurriën Timber,Leeds United,Y,56,3-0,Lucas Perri,Riccardo Calafiori,NaN

In [7]:
goal_logs_prem2 = pd.read_csv('debug_tables/arsenal_goal_logs,_premier_league___fbref.com/table_10.csv')
goal_logs_prem2.head()

,Rk,Date,Round,Venue,Scorer,Opponent,Start,Minute,Score,Goalkeeper,Assist,Notes
0,1,2025-08-31,Matchweek 3,Away,Dominik Szoboszlai,Liverpool,Y,83,0-0,David Raya,NaN,NaN
1,2,2025-09-21,Matchweek 5,Home,Erling Haaland,Manchester City,Y,9,0-0,David Raya,Tijjani Reijnders,NaN
2,3,2025-09-28,Matchweek 6,Away,Nick Woltemade,Newcastle United,Y,34,0-0,David Raya,Sandro Tonali,NaN
3,4,2025-11-08,Matchweek 11,Away,Daniel Ballard,Sunderland,Y,36,0-0,David Raya,Nordi Mukiele,NaN
4,5,2025-11-08,Matchweek 11,Away,Brian Brobbey,Sunderland,N,90+4,1-2,David Raya,NaN,NaN

In [8]:
import pandas as pd

# 1. Load the CSV, skipping the very first row of FBref categories
match_log_cl_goalkeeping = pd.read_csv(
    'debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_9.csv',
    header=0,
    skiprows=[0]
)

# 2. Drop the empty spacer rows and match-summary rows that FBref includes
match_log_cl_goalkeeping = match_log_cl_goalkeeping.dropna(subset=['Date']).reset_index(drop=True)

# 3. View your clean dataframe
match_log_cl_goalkeeping

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,SoTA,GA.1,Saves,Save%,CS,PKatt,PKA,PKsv,PKm,Match Report
0,2025-09-16,18:45 (20:45),League phase,Tue,Away,W,2.0,0.0,es Athletic Club,2.0,0.0,2.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
1,2025-10-01,20:00 (23:00),League phase,Wed,Home,W,2.0,0.0,gr Olympiacos,3.0,0.0,3.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
2,2025-10-21,20:00 (23:00),League phase,Tue,Home,W,4.0,0.0,es Atlético Madrid,1.0,0.0,1.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
3,2025-11-04,18:45 (21:45),League phase,Tue,Away,W,3.0,0.0,cz Slavia Prague,1.0,0.0,1.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
4,2025-11-26,20:00 (00:00),League phase,Wed,Home,W,3.0,1.0,de Bayern Munich,2.0,1.0,1.0,50.0,0.0,0.0,0.0,0.0,0.0,Match Report
5,2025-12-10,21:00 (00:00),League phase,Wed,Away,W,3.0,0.0,be Club Brugge,7.0,0.0,7.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
6,2026-01-20,21:00 (00:00),League phase,Tue,Away,W,3.0,1.0,it Inter,4.0,1.0,3.0,75.0,0.0,0.0,0.0,0.0,0.0,Match Report
7,2026-01-28,20:00 (00:00),League phase,Wed,Home,W,3.0,2.0,kz FC Kairat,1.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,Match Report
8,2026-03-11,18:45 (21:45),Round of 16,Wed,Away,D,1.0,1.0,de Leverkusen,3.0,1.0,2.0,66.7,0.0,0.0,0.0,0.0,0.0,Match Report
9,2026-03-17,20:00 (00:00),Round of 16,Tue,Home,W,2.0,0.0,de Leverkusen,2.0,0.0,2.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
10,2026-04-07,20:00 (23:00),Quarter-finals,Tue,Away,W,1.0,0.0,pt Sporting CP,5.0,0.0,5.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
11,2026-04-15,20:00 (23:00),Quarter-finals,Wed,Home,D,0.0,0.0,pt Sporting CP,1.0,0.0,1.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
12,2026-04-29,21:00 (23:00),Semi-finals,Wed,Away,D,1.0,1.0,es Atlético Madrid,3.0,1.0,3.0,100.0,0.0,1.0,1.0,0.0,0.0,Match Report
13,2026-05-05,20:00 (23:00),Semi-finals,Tue,Home,W,1.0,0.0,es Atlético Madrid,2.0,0.0,2.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report

In [9]:
# 1. Load the CSV, skipping the very first row of FBref categories
match_log_cl_goalkeeping2 = pd.read_csv(
    'debug_tables/arsenal_match_logs_(goalkeeping),_champions_league___fbref.com/table_10.csv',
    header=0,
    skiprows=[0]
)

# 2. Drop the empty spacer rows and match-summary rows that FBref includes
match_log_cl_goalkeeping2 = match_log_cl_goalkeeping2.dropna(subset=['Date']).reset_index(drop=True)

# 3. View your clean dataframe
match_log_cl_goalkeeping2

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,SoTA,GA.1,Saves,Save%,CS,PKatt,PKA,PKsv,PKm,Match Report
0,2025-09-16,18:45 (20:45),League phase,Tue,Home,L,0.0,2.0,es Athletic Club,6.0,2.0,4.0,66.7,0.0,0.0,0.0,0.0,0.0,Match Report
1,2025-10-01,20:00 (23:00),League phase,Wed,Away,L,0.0,2.0,gr Olympiacos,4.0,2.0,2.0,50.0,0.0,0.0,0.0,0.0,0.0,Match Report
2,2025-10-21,20:00 (23:00),League phase,Tue,Away,L,0.0,4.0,es Atlético Madrid,8.0,4.0,4.0,50.0,0.0,0.0,0.0,0.0,0.0,Match Report
3,2025-11-04,18:45 (21:45),League phase,Tue,Home,L,0.0,3.0,cz Slavia Prague,7.0,3.0,5.0,71.4,0.0,1.0,1.0,0.0,0.0,Match Report
4,2025-11-26,20:00 (00:00),League phase,Wed,Away,L,1.0,3.0,de Bayern Munich,8.0,3.0,5.0,62.5,0.0,0.0,0.0,0.0,0.0,Match Report
5,2025-12-10,21:00 (00:00),League phase,Wed,Home,L,0.0,3.0,be Club Brugge,10.0,3.0,7.0,70.0,0.0,0.0,0.0,0.0,0.0,Match Report
6,2026-01-20,21:00 (00:00),League phase,Tue,Home,L,1.0,3.0,it Inter,6.0,3.0,3.0,50.0,0.0,0.0,0.0,0.0,0.0,Match Report
7,2026-01-28,20:00 (00:00),League phase,Wed,Away,L,2.0,3.0,kz FC Kairat,10.0,3.0,7.0,70.0,0.0,0.0,0.0,0.0,0.0,Match Report
8,2026-03-11,18:45 (21:45),Round of 16,Wed,Home,D,1.0,1.0,de Leverkusen,1.0,1.0,1.0,100.0,0.0,1.0,1.0,0.0,0.0,Match Report
9,2026-03-17,20:00 (00:00),Round of 16,Tue,Away,L,0.0,2.0,de Leverkusen,12.0,2.0,10.0,83.3,0.0,0.0,0.0,0.0,0.0,Match Report
10,2026-04-07,20:00 (23:00),Quarter-finals,Tue,Home,L,0.0,1.0,pt Sporting CP,4.0,1.0,3.0,75.0,0.0,0.0,0.0,0.0,0.0,Match Report
11,2026-04-15,20:00 (23:00),Quarter-finals,Wed,Away,D,0.0,0.0,pt Sporting CP,1.0,0.0,1.0,100.0,1.0,0.0,0.0,0.0,0.0,Match Report
12,2026-04-29,21:00 (23:00),Semi-finals,Wed,Home,D,1.0,1.0,es Atlético Madrid,1.0,1.0,1.0,100.0,0.0,1.0,1.0,0.0,0.0,Match Report
13,2026-05-05,20:00 (23:00),Semi-finals,Tue,Away,L,0.0,1.0,es Atlético Madrid,2.0,1.0,1.0,50.0,0.0,0.0,0.0,0.0,0.0,Match Report

In [10]:
match_log_cl_stats = pd.read_csv(
    'debug_tables/arsenal_match_logs_(miscellaneous_stats),_champions_league___fbref.com/table_9.csv',
    header=0,
    skiprows=[0])

match_log_cl_stats = match_log_cl_stats.dropna(subset=['Date']).reset_index(drop=True)

match_log_cl_stats

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,CrdY,...,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Match Report
0,2025-09-16,18:45 (20:45),League phase,Tue,Away,W,2.0,0.0,es Athletic Club,3.0,...,15.0,17.0,2.0,16.0,2.0,15.0,NaN,NaN,0.0,Match Report
1,2025-10-01,20:00 (23:00),League phase,Wed,Home,W,2.0,0.0,gr Olympiacos,3.0,...,14.0,17.0,2.0,16.0,2.0,9.0,NaN,NaN,0.0,Match Report
2,2025-10-21,20:00 (23:00),League phase,Tue,Home,W,4.0,0.0,es Atlético Madrid,1.0,...,14.0,10.0,2.0,15.0,9.0,6.0,NaN,NaN,0.0,Match Report
3,2025-11-04,18:45 (21:45),League phase,Tue,Away,W,3.0,0.0,cz Slavia Prague,4.0,...,12.0,22.0,0.0,15.0,10.0,4.0,NaN,NaN,0.0,Match Report
4,2025-11-26,20:00 (00:00),League phase,Wed,Home,W,3.0,1.0,de Bayern Munich,2.0,...,16.0,13.0,2.0,15.0,11.0,7.0,NaN,NaN,0.0,Match Report
5,2025-12-10,21:00 (00:00),League phase,Wed,Away,W,3.0,0.0,be Club Brugge,2.0,...,9.0,9.0,0.0,26.0,8.0,11.0,NaN,NaN,0.0,Match Report
6,2026-01-20,21:00 (00:00),League phase,Tue,Away,W,3.0,1.0,it Inter,2.0,...,17.0,8.0,3.0,18.0,6.0,6.0,NaN,NaN,0.0,Match Report
7,2026-01-28,20:00 (00:00),League phase,Wed,Home,W,3.0,2.0,kz FC Kairat,1.0,...,14.0,10.0,2.0,19.0,9.0,6.0,NaN,NaN,0.0,Match Report
8,2026-03-11,18:45 (21:45),Round of 16,Wed,Away,D,1.0,1.0,de Leverkusen,3.0,...,10.0,9.0,1.0,21.0,6.0,3.0,NaN,NaN,0.0,Match Report
9,2026-03-17,20:00 (00:00),Round of 16,Tue,Home,W,2.0,0.0,de Leverkusen,0.0,...,4.0,6.0,1.0,16.0,9.0,10.0,NaN,NaN,0.0,Match Report
10,2026-04-07,20:00 (23:00),Quarter-finals,Tue,Away,W,1.0,0.0,pt Sporting CP,0.0,...,10.0,11.0,2.0,16.0,10.0,8.0,NaN,NaN,0.0,Match Report
11,2026-04-15,20:00 (23:00),Quarter-finals,Wed,Home,D,0.0,0.0,pt Sporting CP,0.0,...,7.0,10.0,0.0,18.0,7.0,9.0,NaN,NaN,0.0,Match Report
12,2026-04-29,21:00 (23:00),Semi-finals,Wed,Away,D,1.0,1.0,es Atlético Madrid,0.0,...,11.0,7.0,1.0,7.0,9.0,5.0,NaN,NaN,0.0,Match Report
13,2026-05-05,20:00 (23:00),Semi-finals,Tue,Home,W,1.0,0.0,es Atlético Madrid,1.0,...,10.0,13.0,1.0,14.0,4.0,8.0,NaN,NaN,0.0,Match Report

In [11]:
import pandas as pd

# 1. Read the CSV while skipping the top-most level of categories
match_log_prem_goalkeeping = pd.read_csv(
    'debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_9.csv',
    header=0,
    skiprows=[0]
)

# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
match_log_prem_goalkeeping = match_log_prem_goalkeeping[~match_log_prem_goalkeeping['Date'].isin(['Date', 'For Arsenal'])]

# 3. Drop completely blank rows or the aggregate summary row at the very bottom
match_log_prem_goalkeeping = match_log_prem_goalkeeping.dropna(subset=['Date']).reset_index(drop=True)


match_log_prem_goalkeeping

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,SoTA,GA.1,Saves,Save%,CS,PKatt,PKA,PKsv,PKm,Match Report
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Away,W,1,0,Manchester Utd,7,0,7,100.0,1,0,0,0,0,Match Report
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Home,W,5,0,Leeds United,1,0,1,100.0,1,0,0,0,0,Match Report
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Away,L,0,1,Liverpool,3,1,2,66.7,0,0,0,0,0,Match Report
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Home,W,3,0,Nottingham Forest,1,0,1,100.0,1,0,0,0,0,Match Report
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Home,D,1,1,Manchester City,3,1,2,66.7,0,0,0,0,0,Match Report
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Away,W,2,1,Newcastle United,3,1,2,66.7,0,0,0,0,0,Match Report
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Home,W,2,0,West Ham United,0,0,0,NaN,1,0,0,0,0,Match Report
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Away,W,1,0,Fulham,0,0,0,NaN,1,0,0,0,0,Match Report
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Home,W,1,0,Crystal Palace,1,0,1,100.0,1,0,0,0,0,Match Report
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Away,W,2,0,Burnley,0,0,0,NaN,1,0,0,0,0,Match Report
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Away,D,2,2,Sunderland,2,2,0,0.0,0,0,0,0,0,Match Report
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Home,W,4,1,Tottenham Hotspur,2,1,1,50.0,0,0,0,0,0,Match Report
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Away,D,1,1,Chelsea,4,1,3,75.0,0,0,0,0,0,Match Report
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Home,W,2,0,Brentford,1,0,1,100.0,1,0,0,0,0,Match Report
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Away,L,1,2,Aston Villa,6,2,4,66.7,0,0,0,0,0,Match Report
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Home,W,2,1,Wolves,2,1,1,50.0,0,0,0,0,0,Match Report
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Away,W,1,0,Everton,1,0,1,100.0,1,0,0,0,0,Match Report
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Home,W,2,1,Brighton,3,1,2,66.7,0,0,0,0,0,Match Report
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Home,W,4,1,Aston Villa,3,1,2,66.7,0,0,0,0,0,Match Report
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Away,W,3,2,Bournemouth,3,2,1,33.3,0,0,0,0,0,Match Report
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Home,D,0,0,Liverpool,0,0,0,NaN,1,0,0,0,0,Match Report
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Away,D,0,0,Nottingham Forest,0,0,0,NaN,1,0,0,0,0,Match Report
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Home,L,2,3,Manchester Utd,3,3,0,0.0,0,0,0,0,0,Match Report
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Away,W,4,0,Leeds United,1,0,1,100.0,1,0,0,0,0,Match Report
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Home,W,3,0,Sunderland,2,0,2,100.0,1,0,0,0,0,Match Report
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Away,D,1,1,Brentford,3,1,2,66.7,0,0,0,0,0,Match Report
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Away,D,2,2,Wolves,2,2,0,0.0,0,0,0,0,0,Match Report
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Away,W,4,1,Tottenham Hotspur,5,1,4,80.0,0,0,0,0,0,Match Report
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Home,W,2,1,Chelsea,5,1,3,80.0,0,0,0,0,0,Match Report
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Away,W,1,0,Brighton,2,0,2,100.0,1,0,0,0,0,Match Report
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Home,W,2,0,Everton,3,0,3,100.0,1,0,0,0,0,Match Report
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Home,L,1,2,Bournemouth,3,2,1,33.3,0,0,0,0,0,Match Report
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Away,L,1,2,Manchester City,4,2,2,50.0,0,0,0,0,0,Match Report
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Home,W,1,0,Newcastle United,3,0,3,100.0,1,0,0,0,0,Match Report
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Home,W,3,0,Fulham,1,0,1,100.0,1,0,0,0,0,Match Report
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Away,W,1,0,West Ham United,3,0,3,100.0,1,0,0,0,0,Match Report

In [12]:
import pandas as pd

# 1. Read the CSV while skipping the top-most level of categories
match_log_prem_goalkeeping2 = pd.read_csv(
    'debug_tables/arsenal_match_logs_(goalkeeping),_premier_league___fbref.com/table_10.csv',
    header=0,
    skiprows=[0]
)

# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
match_log_prem_goalkeeping2 = match_log_prem_goalkeeping2[~match_log_prem_goalkeeping2['Date'].isin(['Date', 'For Arsenal'])]

# 3. Drop completely blank rows or the aggregate summary row at the very bottom
match_log_prem_goalkeeping2 = match_log_prem_goalkeeping2.dropna(subset=['Date']).reset_index(drop=True)

#####

match_log_prem_goalkeeping2

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,SoTA,GA.1,Saves,Save%,CS,PKatt,PKA,PKsv,PKm,Match Report
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Home,L,0,1,Manchester Utd,3,1,2,66.7,0,0,0,0,0,Match Report
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Away,L,0,5,Leeds United,4,5,0,0.0,0,1,1,0,0,Match Report
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Home,W,1,0,Liverpool,1,0,1,100.0,1,0,0,0,0,Match Report
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Away,L,0,3,Nottingham Forest,5,3,2,40.0,0,0,0,0,0,Match Report
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Away,D,1,1,Manchester City,3,1,2,66.7,0,0,0,0,0,Match Report
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Home,L,1,2,Newcastle United,7,2,5,71.4,0,0,0,0,0,Match Report
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Away,L,0,2,West Ham United,4,2,3,75.0,0,1,1,0,0,Match Report
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Home,L,0,1,Fulham,5,1,4,80.0,0,0,0,0,0,Match Report
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Away,L,0,1,Crystal Palace,3,1,2,66.7,0,0,0,0,0,Match Report
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Home,L,0,2,Burnley,7,2,5,71.4,0,0,0,0,0,Match Report
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Home,D,2,2,Sunderland,7,2,5,71.4,0,0,0,0,0,Match Report
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Away,L,1,4,Tottenham Hotspur,8,4,4,50.0,0,0,0,0,0,Match Report
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Home,D,1,1,Chelsea,4,1,3,75.0,0,0,0,0,0,Match Report
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Away,L,0,2,Brentford,7,2,5,71.4,0,0,0,0,0,Match Report
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Home,W,2,1,Aston Villa,8,1,7,87.5,0,0,0,0,0,Match Report
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Away,L,1,2,Wolves,4,2,2,50.0,0,0,0,0,0,Match Report
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Home,L,0,1,Everton,0,1,0,NaN,0,1,1,0,0,Match Report
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Away,L,1,2,Brighton,7,2,5,71.4,0,0,0,0,0,Match Report
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Away,L,1,4,Aston Villa,7,4,3,42.9,0,0,0,0,0,Match Report
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Home,L,2,3,Bournemouth,5,3,2,40.0,0,0,0,0,0,Match Report
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Away,D,0,0,Liverpool,4,0,4,100.0,1,0,0,0,0,Match Report
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Home,D,0,0,Nottingham Forest,3,0,3,100.0,1,0,0,0,0,Match Report
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Away,W,3,2,Manchester Utd,5,2,3,60.0,0,0,0,0,0,Match Report
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Home,L,0,4,Leeds United,8,4,4,50.0,0,0,0,0,0,Match Report
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Away,L,0,3,Sunderland,5,3,2,40.0,0,0,0,0,0,Match Report
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Home,D,1,1,Brentford,2,1,1,50.0,0,0,0,0,0,Match Report
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Home,D,2,2,Wolves,4,2,2,50.0,0,0,0,0,0,Match Report
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Home,L,1,4,Tottenham Hotspur,6,4,2,33.3,0,0,0,0,0,Match Report
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Away,L,1,2,Chelsea,5,2,3,60.0,0,0,0,0,0,Match Report
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Home,L,0,1,Brighton,2,1,1,50.0,0,0,0,0,0,Match Report
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Away,L,0,2,Everton,6,2,4,66.7,0,0,0,0,0,Match Report
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Away,W,2,1,Bournemouth,2,1,2,100.0,0,1,1,0,0,Match Report
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Home,W,2,1,Manchester City,2,1,1,50.0,0,0,0,0,0,Match Report
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Away,L,0,1,Newcastle United,4,1,3,75.0,0,0,0,0,0,Match Report
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Away,L,0,3,Fulham,9,3,6,66.7,0,0,0,0,0,Match Report
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Home,L,0,1,West Ham United,2,1,1,50.0,0,0,0,0,0,Match Report

In [13]:

# 1. Read the CSV while skipping the top-most level of categories
match_log_prem_stats = pd.read_csv(
    'debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_9.csv',
    header=0,
    skiprows=[0]
)

# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
match_log_prem_stats = match_log_prem_stats[~match_log_prem_stats['Date'].isin(['Date', 'For Arsenal'])]
match_log_prem_stats = match_log_prem_stats.dropna(subset=['Date']).reset_index(drop=True)

#####

match_log_prem_stats

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,CrdY,...,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Match Report
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Away,W,1,0,Manchester Utd,4,...,19,10,2,11,5,10,NaN,NaN,0,Match Report
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Home,W,5,0,Leeds United,0,...,8,11,0,19,5,9,NaN,NaN,0,Match Report
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Away,L,0,1,Liverpool,2,...,10,7,0,17,9,6,NaN,NaN,0,Match Report
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Home,W,3,0,Nottingham Forest,1,...,8,10,2,20,6,9,NaN,NaN,0,Match Report
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Home,D,1,1,Manchester City,1,...,11,10,4,32,5,14,NaN,NaN,0,Match Report
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Away,W,2,1,Newcastle United,1,...,9,8,0,25,10,6,NaN,NaN,0,Match Report
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Home,W,2,0,West Ham United,0,...,14,14,1,23,7,14,NaN,NaN,0,Match Report
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Away,W,1,0,Fulham,0,...,4,11,2,24,2,5,NaN,NaN,0,Match Report
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Home,W,1,0,Crystal Palace,0,...,6,10,2,10,7,6,NaN,NaN,0,Match Report
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Away,W,2,0,Burnley,1,...,13,10,1,14,6,7,NaN,NaN,0,Match Report
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Away,D,2,2,Sunderland,1,...,13,13,0,22,3,4,NaN,NaN,0,Match Report
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Home,W,4,1,Tottenham Hotspur,1,...,11,15,3,15,11,16,NaN,NaN,0,Match Report
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Away,D,1,1,Chelsea,6,...,13,12,3,15,9,10,NaN,NaN,0,Match Report
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Home,W,2,0,Brentford,0,...,7,8,0,15,6,15,NaN,NaN,0,Match Report
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Away,L,1,2,Aston Villa,2,...,8,10,3,16,10,11,NaN,NaN,0,Match Report
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Home,W,2,1,Wolves,0,...,7,15,1,30,8,3,NaN,NaN,0,Match Report
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Away,W,1,0,Everton,2,...,5,3,1,12,6,9,NaN,NaN,0,Match Report
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Home,W,2,1,Brighton,2,...,7,12,1,19,9,5,NaN,NaN,0,Match Report
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Home,W,4,1,Aston Villa,2,...,18,9,4,12,8,7,NaN,NaN,0,Match Report
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Away,W,3,2,Bournemouth,1,...,8,12,1,20,6,10,NaN,NaN,0,Match Report
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Home,D,0,0,Liverpool,2,...,10,8,2,15,7,6,NaN,NaN,0,Match Report
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Away,D,0,0,Nottingham Forest,1,...,14,8,0,25,4,7,NaN,NaN,0,Match Report
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Home,L,2,3,Manchester Utd,2,...,11,9,3,25,11,7,NaN,NaN,0,Match Report
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Away,W,4,0,Leeds United,1,...,7,10,1,27,6,7,NaN,NaN,0,Match Report
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Home,W,3,0,Sunderland,1,...,11,8,3,19,11,7,NaN,NaN,0,Match Report
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Away,D,1,1,Brentford,2,...,11,12,0,23,4,11,NaN,NaN,0,Match Report
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Away,D,2,2,Wolves,1,...,8,6,3,21,11,12,NaN,NaN,0,Match Report
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Away,W,4,1,Tottenham Hotspur,1,...,11,16,0,15,6,18,NaN,NaN,0,Match Report
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Home,W,2,1,Chelsea,1,...,11,14,0,11,5,10,NaN,NaN,1,Match Report
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Away,W,1,0,Brighton,1,...,12,14,0,7,9,5,NaN,NaN,0,Match Report
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Home,W,2,0,Everton,0,...,11,12,2,21,4,13,NaN,NaN,0,Match Report
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Home,L,1,2,Bournemouth,1,...,12,17,2,22,7,11,NaN,NaN,0,Match Report
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Away,L,1,2,Manchester City,2,...,12,5,4,12,5,14,NaN,NaN,0,Match Report
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Home,W,1,0,Newcastle United,2,...,13,8,2,13,10,8,NaN,NaN,0,Match Report
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Home,W,3,0,Fulham,0,...,7,12,7,9,10,4,NaN,NaN,0,Match Report
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Away,W,1,0,West Ham United,4,...,12,14,0,17,3,4,NaN,NaN,0,Match Report

In [14]:
# 1. Read the CSV while skipping the top-most level of categories
match_log_prem_stats2 = pd.read_csv(
    'debug_tables/arsenal_match_logs_(miscellaneous_stats),_premier_league___fbref.com/table_10.csv',
    header=0,
    skiprows=[0]
)


# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
# match_log_prem_stats = match_log_prem_stats[~match_log_prem_stats['Date'].isin(['Date', 'For Arsenal'])]
match_log_prem_stats2 = match_log_prem_stats2.dropna(subset=['Date']).reset_index(drop=True)

match_log_prem_stats2

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,CrdY,...,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Match Report
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Home,L,0,1,Manchester Utd,1,...,10,19,1,15,5,14,NaN,NaN,0,Match Report
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Away,L,0,5,Leeds United,2,...,11,8,0,5,6,9,NaN,NaN,0,Match Report
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Home,W,1,0,Liverpool,2,...,7,10,1,7,7,9,NaN,NaN,0,Match Report
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Away,L,0,3,Nottingham Forest,1,...,10,7,0,13,10,9,NaN,NaN,0,Match Report
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Away,D,1,1,Manchester City,2,...,10,11,2,4,5,10,NaN,NaN,0,Match Report
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Home,L,1,2,Newcastle United,2,...,8,8,1,15,7,8,NaN,NaN,0,Match Report
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Away,L,0,2,West Ham United,2,...,14,13,1,11,12,7,NaN,NaN,0,Match Report
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Home,L,0,1,Fulham,0,...,11,4,0,17,8,12,NaN,NaN,0,Match Report
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Away,L,0,1,Crystal Palace,0,...,11,6,1,10,11,9,NaN,NaN,0,Match Report
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Home,L,0,2,Burnley,2,...,10,12,0,13,8,9,NaN,NaN,0,Match Report
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Home,D,2,2,Sunderland,2,...,13,13,2,11,5,9,NaN,NaN,0,Match Report
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Away,L,1,4,Tottenham Hotspur,3,...,15,10,1,7,7,13,NaN,NaN,0,Match Report
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Home,D,1,1,Chelsea,1,...,12,13,1,15,6,5,NaN,NaN,0,Match Report
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Away,L,0,2,Brentford,1,...,9,7,0,12,12,13,NaN,NaN,0,Match Report
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Home,W,2,1,Aston Villa,0,...,10,8,0,13,5,10,NaN,NaN,0,Match Report
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Away,L,1,2,Wolves,4,...,15,6,1,8,5,5,NaN,NaN,2,Match Report
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Home,L,0,1,Everton,2,...,4,5,0,14,8,12,NaN,NaN,0,Match Report
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Away,L,1,2,Brighton,3,...,13,7,1,10,5,14,NaN,NaN,1,Match Report
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Away,L,1,4,Aston Villa,3,...,9,17,0,12,3,4,NaN,NaN,0,Match Report
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Home,L,2,3,Bournemouth,3,...,13,8,1,22,4,12,NaN,NaN,0,Match Report
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Away,D,0,0,Liverpool,2,...,9,10,1,9,8,7,NaN,NaN,0,Match Report
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Home,D,0,0,Nottingham Forest,1,...,8,14,1,25,6,5,NaN,NaN,0,Match Report
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Away,W,3,2,Manchester Utd,0,...,9,11,0,5,6,9,NaN,NaN,1,Match Report
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Home,L,0,4,Leeds United,1,...,10,7,0,19,10,6,NaN,NaN,0,Match Report
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Away,L,0,3,Sunderland,2,...,8,11,1,13,6,7,NaN,NaN,0,Match Report
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Home,D,1,1,Brentford,3,...,12,11,0,15,12,6,NaN,NaN,0,Match Report
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Home,D,2,2,Wolves,2,...,6,8,1,14,8,12,NaN,NaN,0,Match Report
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Home,L,1,4,Tottenham Hotspur,2,...,17,11,0,11,13,13,NaN,NaN,0,Match Report
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Away,L,1,2,Chelsea,5,...,14,10,1,18,12,9,NaN,NaN,0,Match Report
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Home,L,0,1,Brighton,4,...,14,12,3,29,12,16,NaN,NaN,0,Match Report
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Away,L,0,2,Everton,0,...,12,11,1,9,16,8,NaN,NaN,0,Match Report
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Away,W,2,1,Bournemouth,3,...,18,11,0,8,8,11,NaN,NaN,0,Match Report
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Home,W,2,1,Manchester City,2,...,5,11,0,16,8,9,NaN,NaN,0,Match Report
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Away,L,0,1,Newcastle United,2,...,10,13,1,19,12,7,NaN,NaN,0,Match Report
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Away,L,0,3,Fulham,1,...,12,6,0,12,5,17,NaN,NaN,0,Match Report
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Home,L,0,1,West Ham United,3,...,14,11,0,14,3,7,NaN,NaN,0,Match Report

In [15]:
match_log_prem_shooting = pd.read_csv(
    'debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_9.csv',
    header=0,
    skiprows=[0]
)


# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
match_log_prem_shooting = match_log_prem_shooting[~match_log_prem_shooting['Date'].isin(['Date', 'For Arsenal'])]
match_log_prem_shooting = match_log_prem_shooting.dropna(subset=['Date']).reset_index(drop=True)

match_log_prem_shooting

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,Gls,Sh,SoT,SoT%,G/Sh,G/SoT,PK,PKatt,Match Report
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Away,W,1,0,Manchester Utd,1,9,3,33.3,0.11,0.33,0,0,Match Report
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Home,W,5,0,Leeds United,5,18,5,27.8,0.22,0.80,1,1,Match Report
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Away,L,0,1,Liverpool,0,11,1,9.1,0.00,0.00,0,0,Match Report
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Home,W,3,0,Nottingham Forest,3,16,5,31.3,0.19,0.60,0,0,Match Report
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Home,D,1,1,Manchester City,1,12,3,25.0,0.08,0.33,0,0,Match Report
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Away,W,2,1,Newcastle United,2,20,7,35.0,0.10,0.29,0,0,Match Report
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Home,W,2,0,West Ham United,2,21,5,23.8,0.05,0.20,1,1,Match Report
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Away,W,1,0,Fulham,1,16,5,31.3,0.06,0.20,0,0,Match Report
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Home,W,1,0,Crystal Palace,1,10,3,30.0,0.10,0.33,0,0,Match Report
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Away,W,2,0,Burnley,2,12,8,66.7,0.17,0.25,0,0,Match Report
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Away,D,2,2,Sunderland,2,17,7,41.2,0.12,0.29,0,0,Match Report
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Home,W,4,1,Tottenham Hotspur,4,17,8,47.1,0.24,0.50,0,0,Match Report
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Away,D,1,1,Chelsea,1,8,4,50.0,0.13,0.25,0,0,Match Report
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Home,W,2,0,Brentford,2,15,7,46.7,0.13,0.29,0,0,Match Report
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Away,L,1,2,Aston Villa,1,15,9,60.0,0.07,0.11,0,0,Match Report
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Home,W,2,1,Wolves,0,16,2,12.5,0.00,0.00,0,0,Match Report
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Away,W,1,0,Everton,1,13,2,15.4,0.00,0.00,1,1,Match Report
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Home,W,2,1,Brighton,1,24,6,25.0,0.04,0.17,0,0,Match Report
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Home,W,4,1,Aston Villa,4,22,7,31.8,0.18,0.57,0,0,Match Report
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Away,W,3,2,Bournemouth,3,12,5,41.7,0.25,0.60,0,0,Match Report
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Home,D,0,0,Liverpool,0,9,4,44.4,0.00,0.00,0,0,Match Report
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Away,D,0,0,Nottingham Forest,0,15,3,20.0,0.00,0.00,0,0,Match Report
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Home,L,2,3,Manchester Utd,1,15,4,26.7,0.07,0.25,0,0,Match Report
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Away,W,4,0,Leeds United,4,14,8,57.1,0.29,0.50,0,0,Match Report
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Home,W,3,0,Sunderland,3,16,5,31.3,0.19,0.60,0,0,Match Report
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Away,D,1,1,Brentford,1,7,2,28.6,0.14,0.50,0,0,Match Report
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Away,D,2,2,Wolves,2,10,4,40.0,0.20,0.50,0,0,Match Report
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Away,W,4,1,Tottenham Hotspur,4,20,7,35.0,0.20,0.57,0,0,Match Report
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Home,W,2,1,Chelsea,2,12,5,41.7,0.17,0.40,0,0,Match Report
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Away,W,1,0,Brighton,1,7,2,28.6,0.14,0.50,0,0,Match Report
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Home,W,2,0,Everton,2,25,7,28.0,0.08,0.29,0,0,Match Report
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Home,L,1,2,Bournemouth,1,15,3,20.0,0.00,0.00,1,1,Match Report
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Away,L,1,2,Manchester City,1,9,3,33.3,0.11,0.33,0,0,Match Report
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Home,W,1,0,Newcastle United,1,11,4,36.4,0.09,0.25,0,0,Match Report
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Home,W,3,0,Fulham,3,18,9,50.0,0.17,0.33,0,0,Match Report
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Away,W,1,0,West Ham United,1,15,4,26.7,0.07,0.25,0,0,Match Report

In [16]:
match_log_prem_shooting2 = pd.read_csv(
    'debug_tables/arsenal_match_logs_(shooting),_premier_league___fbref.com/table_10.csv',
    header=0,
    skiprows=[0]
)


# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
match_log_prem_shooting2 = match_log_prem_shooting2[~match_log_prem_shooting2['Date'].isin(['Date', 'For Arsenal'])]
match_log_prem_shooting2 = match_log_prem_shooting2.dropna(subset=['Date']).reset_index(drop=True)


match_log_prem_shooting2

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,Gls,Sh,SoT,SoT%,G/Sh,G/SoT,PK,PKatt,Match Report
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Home,L,0,1,Manchester Utd,0,22,7,31.8,0.00,0.00,0,0,Match Report
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Away,L,0,5,Leeds United,0,3,1,33.3,0.00,0.00,0,0,Match Report
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Home,W,1,0,Liverpool,1,9,3,33.3,0.11,0.33,0,0,Match Report
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Away,L,0,3,Nottingham Forest,0,5,1,20.0,0.00,0.00,0,0,Match Report
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Away,D,1,1,Manchester City,1,5,3,60.0,0.20,0.33,0,0,Match Report
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Home,L,1,2,Newcastle United,1,8,3,37.5,0.13,0.33,0,0,Match Report
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Away,L,0,2,West Ham United,0,4,0,0.0,0.00,NaN,0,0,Match Report
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Home,L,0,1,Fulham,0,9,0,0.0,0.00,NaN,0,0,Match Report
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Away,L,0,1,Crystal Palace,0,7,1,14.3,0.00,0.00,0,0,Match Report
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Home,L,0,2,Burnley,0,3,0,0.0,0.00,NaN,0,0,Match Report
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Home,D,2,2,Sunderland,2,6,2,33.3,0.33,1.00,0,0,Match Report
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Away,L,1,4,Tottenham Hotspur,1,3,2,66.7,0.33,0.50,0,0,Match Report
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Home,D,1,1,Chelsea,1,11,4,36.4,0.09,0.25,0,0,Match Report
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Away,L,0,2,Brentford,0,6,1,16.7,0.00,0.00,0,0,Match Report
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Home,W,2,1,Aston Villa,2,15,6,40.0,0.13,0.33,0,0,Match Report
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Away,L,1,2,Wolves,1,3,2,66.7,0.33,0.50,0,0,Match Report
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Home,L,0,1,Everton,0,5,1,20.0,0.00,0.00,0,0,Match Report
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Away,L,1,2,Brighton,1,8,3,37.5,0.13,0.33,0,0,Match Report
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Away,L,1,4,Aston Villa,1,11,3,27.3,0.09,0.33,0,0,Match Report
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Home,L,2,3,Bournemouth,2,15,3,20.0,0.13,0.67,0,0,Match Report
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Away,D,0,0,Liverpool,0,8,0,0.0,0.00,NaN,0,0,Match Report
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Home,D,0,0,Nottingham Forest,0,6,0,0.0,0.00,NaN,0,0,Match Report
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Away,W,3,2,Manchester Utd,3,10,3,30.0,0.30,1.00,0,0,Match Report
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Home,L,0,4,Leeds United,0,3,1,33.3,0.00,0.00,0,0,Match Report
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Away,L,0,3,Sunderland,0,5,3,60.0,0.00,0.00,0,0,Match Report
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Home,D,1,1,Brentford,1,12,3,25.0,0.08,0.33,0,0,Match Report
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Home,D,2,2,Wolves,2,5,2,40.0,0.40,1.00,0,0,Match Report
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Home,L,1,4,Tottenham Hotspur,1,6,5,83.3,0.17,0.20,0,0,Match Report
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Away,L,1,2,Chelsea,0,9,3,33.3,0.00,0.00,0,0,Match Report
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Home,L,0,1,Brighton,0,11,3,27.3,0.00,0.00,0,0,Match Report
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Away,L,0,2,Everton,0,9,3,33.3,0.00,0.00,0,0,Match Report
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Away,W,2,1,Bournemouth,2,8,3,37.5,0.25,0.67,0,0,Match Report
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Home,W,2,1,Manchester City,2,15,5,33.3,0.13,0.40,0,0,Match Report
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Away,L,0,1,Newcastle United,0,13,3,23.1,0.00,0.00,0,0,Match Report
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Away,L,0,3,Fulham,0,10,1,10.0,0.00,0.00,0,0,Match Report
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Home,L,0,1,West Ham United,0,9,3,33.3,0.00,0.00,0,0,Match Report

In [17]:


match_log_cl_shooting = pd.read_csv(
    'debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_9.csv',
    header=0,
    skiprows=[0]
)


match_log_cl_shooting = match_log_cl_shooting.dropna(subset=['Date']).reset_index(drop=True)

#####

match_log_cl_shooting

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,Gls,Sh,SoT,SoT%,G/Sh,G/SoT,PK,PKatt,Match Report
0,2025-09-16,18:45 (20:45),League phase,Tue,Away,W,2.0,0.0,es Athletic Club,2.0,11.0,6.0,54.5,0.18,0.33,0.0,0.0,Match Report
1,2025-10-01,20:00 (23:00),League phase,Wed,Home,W,2.0,0.0,gr Olympiacos,2.0,16.0,5.0,31.3,0.13,0.40,0.0,0.0,Match Report
2,2025-10-21,20:00 (23:00),League phase,Tue,Home,W,4.0,0.0,es Atlético Madrid,4.0,19.0,8.0,42.1,0.21,0.50,0.0,0.0,Match Report
3,2025-11-04,18:45 (21:45),League phase,Tue,Away,W,3.0,0.0,cz Slavia Prague,3.0,14.0,8.0,57.1,0.14,0.25,1.0,1.0,Match Report
4,2025-11-26,20:00 (00:00),League phase,Wed,Home,W,3.0,1.0,de Bayern Munich,3.0,12.0,8.0,66.7,0.25,0.38,0.0,0.0,Match Report
5,2025-12-10,21:00 (00:00),League phase,Wed,Away,W,3.0,0.0,be Club Brugge,3.0,20.0,11.0,55.0,0.15,0.27,0.0,0.0,Match Report
6,2026-01-20,21:00 (00:00),League phase,Tue,Away,W,3.0,1.0,it Inter,3.0,17.0,6.0,35.3,0.18,0.50,0.0,0.0,Match Report
7,2026-01-28,20:00 (00:00),League phase,Wed,Home,W,3.0,2.0,kz FC Kairat,3.0,25.0,11.0,44.0,0.12,0.27,0.0,0.0,Match Report
8,2026-03-11,18:45 (21:45),Round of 16,Wed,Away,D,1.0,1.0,de Leverkusen,1.0,6.0,2.0,33.3,0.00,0.00,1.0,1.0,Match Report
9,2026-03-17,20:00 (00:00),Round of 16,Tue,Home,W,2.0,0.0,de Leverkusen,2.0,21.0,12.0,57.1,0.10,0.17,0.0,0.0,Match Report
10,2026-04-07,20:00 (23:00),Quarter-finals,Tue,Away,W,1.0,0.0,pt Sporting CP,1.0,7.0,4.0,57.1,0.14,0.25,0.0,0.0,Match Report
11,2026-04-15,20:00 (23:00),Quarter-finals,Wed,Home,D,0.0,0.0,pt Sporting CP,0.0,15.0,1.0,6.7,0.00,0.00,0.0,0.0,Match Report
12,2026-04-29,21:00 (23:00),Semi-finals,Wed,Away,D,1.0,1.0,es Atlético Madrid,1.0,11.0,2.0,18.2,0.00,0.00,1.0,1.0,Match Report
13,2026-05-05,20:00 (23:00),Semi-finals,Tue,Home,W,1.0,0.0,es Atlético Madrid,1.0,13.0,2.0,15.4,0.08,0.50,0.0,0.0,Match Report

In [18]:
match_log_cl_shooting2 = pd.read_csv(
    'debug_tables/arsenal_match_logs_(shooting),_champions_league___fbref.com/table_10.csv',
    header=0,
    skiprows=[0]
)


match_log_cl_shooting2 = match_log_cl_shooting2.dropna(subset=['Date']).reset_index(drop=True)


#####

match_log_cl_shooting2

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,Gls,Sh,SoT,SoT%,G/Sh,G/SoT,PK,PKatt,Match Report
0,2025-09-16,18:45 (20:45),League phase,Tue,Home,L,0.0,2.0,es Athletic Club,0.0,11.0,2.0,18.2,0.00,0.00,0.0,0.0,Match Report
1,2025-10-01,20:00 (23:00),League phase,Wed,Away,L,0.0,2.0,gr Olympiacos,0.0,10.0,3.0,30.0,0.00,0.00,0.0,0.0,Match Report
2,2025-10-21,20:00 (23:00),League phase,Tue,Away,L,0.0,4.0,es Atlético Madrid,0.0,11.0,1.0,9.1,0.00,0.00,0.0,0.0,Match Report
3,2025-11-04,18:45 (21:45),League phase,Tue,Home,L,0.0,3.0,cz Slavia Prague,0.0,9.0,1.0,11.1,0.00,0.00,0.0,0.0,Match Report
4,2025-11-26,20:00 (00:00),League phase,Wed,Away,L,1.0,3.0,de Bayern Munich,1.0,8.0,2.0,25.0,0.13,0.50,0.0,0.0,Match Report
5,2025-12-10,21:00 (00:00),League phase,Wed,Home,L,0.0,3.0,be Club Brugge,0.0,18.0,7.0,38.9,0.00,0.00,0.0,0.0,Match Report
6,2026-01-20,21:00 (00:00),League phase,Tue,Home,L,1.0,3.0,it Inter,1.0,18.0,4.0,22.2,0.06,0.25,0.0,0.0,Match Report
7,2026-01-28,20:00 (00:00),League phase,Wed,Away,L,2.0,3.0,kz FC Kairat,2.0,4.0,2.0,50.0,0.25,0.50,1.0,1.0,Match Report
8,2026-03-11,18:45 (21:45),Round of 16,Wed,Home,D,1.0,1.0,de Leverkusen,1.0,10.0,3.0,30.0,0.10,0.33,0.0,0.0,Match Report
9,2026-03-17,20:00 (00:00),Round of 16,Tue,Away,L,0.0,2.0,de Leverkusen,0.0,9.0,2.0,22.2,0.00,0.00,0.0,0.0,Match Report
10,2026-04-07,20:00 (23:00),Quarter-finals,Tue,Home,L,0.0,1.0,pt Sporting CP,0.0,11.0,5.0,45.5,0.00,0.00,0.0,0.0,Match Report
11,2026-04-15,20:00 (23:00),Quarter-finals,Wed,Away,D,0.0,0.0,pt Sporting CP,0.0,8.0,1.0,12.5,0.00,0.00,0.0,0.0,Match Report
12,2026-04-29,21:00 (23:00),Semi-finals,Wed,Home,D,1.0,1.0,es Atlético Madrid,1.0,18.0,4.0,22.2,0.00,0.00,1.0,1.0,Match Report
13,2026-05-05,20:00 (23:00),Semi-finals,Tue,Away,L,0.0,1.0,es Atlético Madrid,0.0,9.0,2.0,22.2,0.00,0.00,0.0,0.0,Match Report

In [19]:
score_and_fixtures_prem = pd.read_csv(
    'debug_tables/arsenal_scores_and_fixtures,_premier_league___fbref.com/table_9.csv',
)

# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
score_and_fixtures_prem = score_and_fixtures_prem[~score_and_fixtures_prem['Date'].isin(['Date', 'For Arsenal'])]
score_and_fixtures_prem = score_and_fixtures_prem.dropna(subset=['Date']).reset_index(drop=True)


#####

score_and_fixtures_prem

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,Poss,Attendance,Captain,Formation,Opp Formation,Referee,Match Report,Notes
0,2025-08-17,16:30 (19:30),Matchweek 1,Sun,Away,W,1,0,Manchester Utd,39,73475,Martin Ødegaard,4-3-3,3-4-3,Simon Hooper,Match Report,NaN
1,2025-08-23,17:30 (20:30),Matchweek 2,Sat,Home,W,5,0,Leeds United,68,60110,Martin Ødegaard,4-3-3,4-3-3,Jarred Gillett,Match Report,NaN
2,2025-08-31,16:30 (19:30),Matchweek 3,Sun,Away,L,0,1,Liverpool,47,60455,Gabriel Magalhães,4-3-3,4-2-3-1,Chris Kavanagh,Match Report,NaN
3,2025-09-13,12:30 (15:30),Matchweek 4,Sat,Home,W,3,0,Nottingham Forest,54,60167,Martin Ødegaard,4-3-3,4-2-3-1,Darren England,Match Report,NaN
4,2025-09-21,16:30 (19:30),Matchweek 5,Sun,Home,D,1,1,Manchester City,67,60161,Gabriel Magalhães,4-3-3,4-1-4-1,Stuart Attwell,Match Report,NaN
5,2025-09-28,16:30 (19:30),Matchweek 6,Sun,Away,W,2,1,Newcastle United,64,52199,Bukayo Saka,4-2-3-1,4-3-3,Jarred Gillett,Match Report,NaN
6,2025-10-04,15:00 (18:00),Matchweek 7,Sat,Home,W,2,0,West Ham United,68,60181,Martin Ødegaard,4-3-3,4-1-4-1,John Brooks,Match Report,NaN
7,2025-10-18,17:30 (20:30),Matchweek 8,Sat,Away,W,1,0,Fulham,63,27736,Bukayo Saka,4-3-3,4-2-3-1,Anthony Taylor,Match Report,NaN
8,2025-10-26,14:00 (18:00),Matchweek 9,Sun,Home,W,1,0,Crystal Palace,60,60103,Bukayo Saka,4-3-3,3-4-3,Thomas Bramall,Match Report,NaN
9,2025-11-01,15:00 (19:00),Matchweek 10,Sat,Away,W,2,0,Burnley,54,21538,Bukayo Saka,4-3-3,5-4-1,Chris Kavanagh,Match Report,NaN
10,2025-11-08,17:30 (21:30),Matchweek 11,Sat,Away,D,2,2,Sunderland,65,46799,Bukayo Saka,4-2-3-1,5-4-1,Craig Pawson,Match Report,NaN
11,2025-11-23,16:30 (20:30),Matchweek 12,Sun,Home,W,4,1,Tottenham Hotspur,57,60345,Bukayo Saka,4-2-3-1,3-4-3,Michael Oliver,Match Report,NaN
12,2025-11-30,16:30 (20:30),Matchweek 13,Sun,Away,D,1,1,Chelsea,62,39820,Bukayo Saka,4-3-3,4-2-3-1,Anthony Taylor,Match Report,NaN
13,2025-12-03,19:30 (23:30),Matchweek 14,Wed,Home,W,2,0,Brentford,62,60110,Martin Ødegaard,4-3-3,5-3-2,Tony Harrington,Match Report,NaN
14,2025-12-06,12:30 (16:30),Matchweek 15,Sat,Away,L,1,2,Aston Villa,53,42888,Martin Ødegaard,4-3-3,4-2-3-1,Peter Bankes,Match Report,NaN
15,2025-12-13,20:00 (00:00),Matchweek 16,Sat,Home,W,2,1,Wolves,69,60242,Bukayo Saka,4-3-3,3-5-2,Robert Jones,Match Report,NaN
16,2025-12-20,20:00 (00:00),Matchweek 17,Sat,Away,W,1,0,Everton,65,52513,Martin Ødegaard,4-3-3,4-2-3-1,Samuel Barrott,Match Report,NaN
17,2025-12-27,15:00 (19:00),Matchweek 18,Sat,Home,W,2,1,Brighton,53,60209,Martin Ødegaard,4-3-3,3-4-3,John Brooks,Match Report,NaN
18,2025-12-30,20:15 (00:15),Matchweek 19,Tue,Home,W,4,1,Aston Villa,47,60279,Martin Ødegaard,4-3-3,4-2-3-1,Darren England,Match Report,NaN
19,2026-01-03,17:30 (21:30),Matchweek 20,Sat,Away,W,3,2,Bournemouth,57,11240,Martin Ødegaard,4-3-3,4-2-3-1,Chris Kavanagh,Match Report,NaN
20,2026-01-08,20:00 (00:00),Matchweek 21,Thu,Home,D,0,0,Liverpool,48,60258,Martin Ødegaard,4-3-3,4-2-3-1,Anthony Taylor,Match Report,NaN
21,2026-01-17,17:30 (21:30),Matchweek 22,Sat,Away,D,0,0,Nottingham Forest,61,30729,Martin Ødegaard,4-3-3,4-2-3-1,Michael Oliver,Match Report,NaN
22,2026-01-25,16:30 (20:30),Matchweek 23,Sun,Home,L,2,3,Manchester Utd,57,60296,Martin Ødegaard,4-3-3,4-2-3-1,Craig Pawson,Match Report,NaN
23,2026-01-31,15:00 (19:00),Matchweek 24,Sat,Away,W,4,0,Leeds United,51,36858,Gabriel Magalhães,4-2-3-1,3-4-3,Stuart Attwell,Match Report,NaN
24,2026-02-07,15:00 (19:00),Matchweek 25,Sat,Home,W,3,0,Sunderland,50,60312,Gabriel Magalhães,4-3-3,4-2-3-1,Samuel Barrott,Match Report,NaN
25,2026-02-12,20:00 (00:00),Matchweek 26,Thu,Away,D,1,1,Brentford,60,17224,Gabriel Magalhães,4-2-3-1,4-2-3-1,John Brooks,Match Report,NaN
26,2026-02-18,20:00 (00:00),Matchweek 31,Wed,Away,D,2,2,Wolves,58,29843,Bukayo Saka,4-2-3-1,3-4-3,Paul Tierney,Match Report,NaN
27,2026-02-22,16:30 (20:30),Matchweek 27,Sun,Away,W,4,1,Tottenham Hotspur,61,61439,Bukayo Saka,4-2-3-1,3-5-2,Peter Bankes,Match Report,NaN
28,2026-03-01,16:30 (20:30),Matchweek 28,Sun,Home,W,2,1,Chelsea,41,60296,Bukayo Saka,4-2-3-1,4-3-3,Darren England,Match Report,NaN
29,2026-03-04,19:30 (23:30),Matchweek 29,Wed,Away,W,1,0,Brighton,40,31575,Bukayo Saka,4-2-3-1,4-2-3-1,Chris Kavanagh,Match Report,NaN
30,2026-03-14,17:30 (21:30),Matchweek 30,Sat,Home,W,2,0,Everton,65,60176,Bukayo Saka,4-2-3-1,4-2-3-1,Andy Madley,Match Report,NaN
31,2026-04-11,12:30 (15:30),Matchweek 32,Sat,Home,L,1,2,Bournemouth,53,60210,Declan Rice,4-2-3-1,4-2-3-1,Michael Oliver,Match Report,NaN
32,2026-04-19,16:30 (19:30),Matchweek 33,Sun,Away,L,1,2,Manchester City,41,52523,Martin Ødegaard,4-3-3,4-2-3-1,Anthony Taylor,Match Report,NaN
33,2026-04-25,17:30 (20:30),Matchweek 34,Sat,Home,W,1,0,Newcastle United,45,60204,Martin Ødegaard,4-3-3,4-1-4-1,Samuel Barrott,Match Report,NaN
34,2026-05-02,17:30 (20:30),Matchweek 35,Sat,Home,W,3,0,Fulham,54,60196,Bukayo Saka,4-2-3-1,4-2-3-1,Jarred Gillett,Match Report,NaN
35,2026-05-10,16:30 (19:30),Matchweek 36,Sun,Away,W,1,0,West Ham United,64,60429,Bukayo Saka,4-2-3-1,3-4-3,Chris Kavanagh,Match Report,NaN
36,2026-05-18,20:00 (23:00),Matchweek 37,Mon,Home,NaN,NaN,NaN,Burnley,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN
37,2026-05-24,16:00 (19:00),Matchweek 38,Sun,Away,NaN,NaN,NaN,Crystal Palace,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN

In [21]:
score_and_fixtures_cl = pd.read_csv(
    'debug_tables/arsenal_scores_and_fixtures,_champions_league___fbref.com/table_9.csv',
)

# 2. Filter out any mid-table rows that repeat the column names or category headers
# This also dynamically cleans out any row that contains 'Date' or 'For Arsenal' in the Date column
score_and_fixtures_cl = score_and_fixtures_cl[~score_and_fixtures_cl['Date'].isin(['Date', 'For Arsenal'])]
score_and_fixtures_cl = score_and_fixtures_cl.dropna(subset=['Date']).reset_index(drop=True)


#####

score_and_fixtures_cl

,Date,Time,Round,Day,Venue,Result,GF,GA,Opponent,Poss,Attendance,Captain,Formation,Opp Formation,Referee,Match Report,Notes
0,2025-09-16,18:45 (20:45),League phase,Tue,Away,W,2.0,0.0,es Athletic Club,62.0,51059.0,Gabriel Magalhães,4-3-3,4-2-3-1,Donatas Rumšas,Match Report,NaN
1,2025-10-01,20:00 (23:00),League phase,Wed,Home,W,2.0,0.0,gr Olympiacos,61.0,56820.0,Martin Ødegaard,4-3-3,4-2-3-1,François Letexier,Match Report,NaN
2,2025-10-21,20:00 (23:00),League phase,Tue,Home,W,4.0,0.0,es Atlético Madrid,51.0,59200.0,Bukayo Saka,4-2-3-1,4-4-2,Davide Massa,Match Report,NaN
3,2025-11-04,18:45 (21:45),League phase,Tue,Away,W,3.0,0.0,cz Slavia Prague,57.0,19222.0,Bukayo Saka,4-3-3,3-4-3,Əliyar Ağayev,Match Report,NaN
4,2025-11-26,20:00 (00:00),League phase,Wed,Home,W,3.0,1.0,de Bayern Munich,40.0,58780.0,Bukayo Saka,4-3-3,4-2-3-1,Marco Guida,Match Report,NaN
5,2025-12-10,21:00 (00:00),League phase,Wed,Away,W,3.0,0.0,be Club Brugge,51.0,26464.0,Martin Ødegaard,4-3-3,4-2-3-1,Sven Jablonski,Match Report,NaN
6,2026-01-20,21:00 (00:00),League phase,Tue,Away,W,3.0,1.0,it Inter,49.0,72649.0,Bukayo Saka,4-3-3,3-5-2,João Pinheiro,Match Report,NaN
7,2026-01-28,20:00 (00:00),League phase,Wed,Home,W,3.0,2.0,kz FC Kairat,66.0,50200.0,Ben White,4-3-3,3-4-3,Urs Schnyder,Match Report,NaN
8,2026-03-11,18:45 (21:45),Round of 16,Wed,Away,D,1.0,1.0,de Leverkusen,55.0,30210.0,Bukayo Saka,4-2-3-1,3-4-3,Halil Umut Meler,Match Report,Leg 1 of 2
9,2026-03-17,20:00 (00:00),Round of 16,Tue,Home,W,2.0,0.0,de Leverkusen,42.0,57537.0,Bukayo Saka,4-2-3-1,3-4-3,Danny Makkelie,Match Report,Leg 2 of 2; Arsenal won
10,2026-04-07,20:00 (23:00),Quarter-finals,Tue,Away,W,1.0,0.0,pt Sporting CP,56.0,50804.0,Martin Ødegaard,4-3-3,4-2-3-1,Daniel Siebert,Match Report,Leg 1 of 2
11,2026-04-15,20:00 (23:00),Quarter-finals,Wed,Home,D,0.0,0.0,pt Sporting CP,50.0,58249.0,Declan Rice,4-2-3-1,4-2-3-1,François Letexier,Match Report,Leg 2 of 2; Arsenal won
12,2026-04-29,21:00 (23:00),Semi-finals,Wed,Away,D,1.0,1.0,es Atlético Madrid,48.0,68421.0,Martin Ødegaard,4-3-3,4-4-2,Danny Makkelie,Match Report,Leg 1 of 2
13,2026-05-05,20:00 (23:00),Semi-finals,Tue,Home,W,1.0,0.0,es Atlético Madrid,53.0,58874.0,Bukayo Saka,4-2-3-1,4-4-2,Daniel Siebert,Match Report,Leg 2 of 2; Arsenal won
14,2026-05-30,18:00 (20:00),Final,Sat,Away,NaN,NaN,NaN,fr Paris Saint-Germain,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN